name: http3
version: 0.1.0

dependencies:
- base
- network
- bytestring
- text
- vector

default-extensions:
- BinaryLiterals
- DerivingStrategies
- GeneralizedNewtypeDeriving
- ViewPatterns
- OverloadedStrings

library:
  source-dirs: src
